background_image: 'assets/default_background.png'
cameras:
  - id: 0
    rtsp_url: 'rtsp://admin:Gaura108@192.168.87.76:554/h264Preview_01_main'
    https:
      ip: '192.168.87.76'
      username: 'admin'
      password: 'Gaura108'
  # - id: 1
  #   rtsp_url: 'rtsp://admin:Gaura108@192.168.87.77:554/h264Preview_01_main'
  #   https:
  #     ip: '192.168.87.77'
  #     username: 'admin'
  #     password: 'Gaura108'
  # - id: 2
  #   rtsp_url: 'rtsp://admin:Gaura108@192.168.87.78:554/h264Preview_01_main'
  #   https:
  #     ip: '192.168.87.78'
  #     username: 'admin'
  #     password: 'Gaura108'

modes:
  dual_0_topleft:
    type: 'dual_view'
    pos0: [859, 483]
    pos1: [0, 0]
    scale0: 33
    scale1: 80
  dual_1_topleft:
    type: 'dual_view'
    pos0: [859, 483]
    pos1: [0, 0]
    scale1: 33
    scale0: 80
  fullscreen_0:
    type: 'full_screen'
    pos: [0, 0]
    scale: 100
  fullscreen_1:
    type: 'full_screen'
    pos: [0, 0]
    scale: 100
  left_column_12_right_main_0:
    type: 'left_column_right_main'
    cam_left_top: 0
    pos_left_top: [0, 0]
    cam_left_bottom: 0
    pos_left_bottom: [0, 540]
    cam_right: 0
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_21_right_main_0:
    type: 'left_column_right_main'
    cam_left_top: 2
    pos_left_top: [0, 0]
    cam_left_bottom: 1
    pos_left_bottom: [0, 540]
    cam_right: 0
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_02_right_main_1:
    type: 'left_column_right_main'
    cam_left_top: 0
    pos_left_top: [0, 0]
    cam_left_bottom: 2
    pos_left_bottom: [0, 540]
    cam_right: 1
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_20_right_main_1:
    type: 'left_column_right_main'
    cam_left_top: 2
    pos_left_top: [0, 0]
    cam_left_bottom: 0
    pos_left_bottom: [0, 540]
    cam_right: 1
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_01_right_main_2:
    type: 'left_column_right_main'
    cam_left_top: 0
    pos_left_top: [0, 0]
    cam_left_bottom: 1
    pos_left_bottom: [0, 540]
    cam_right: 2
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_10_right_main_2:
    type: 'left_column_right_main'
    cam_left_top: 1
    pos_left_top: [0, 0]
    cam_left_bottom: 0
    pos_left_bottom: [0, 540]
    cam_right: 2
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
