background_image: 'assets/default_background.png'
cameras:
  - id: 0
    rtsp_url: 'rtsp://admin:Gaura108@192.168.87.76:554/h264Preview_01_main'
    https:
      ip: '192.168.87.76'
      username: 'admin'
      password: 'Gaura108'
  # - id: 1
  #   rtsp_url: 'rtsp://admin:Gaura108@192.168.87.77:554/h264Preview_01_main'
  #   https:
  #     ip: '192.168.87.77'
  #     username: 'admin'
  #     password: 'Gaura108'
  # - id: 2
  #   rtsp_url: 'rtsp://admin:Gaura108@192.168.87.78:554/h264Preview_01_main'
  #   https:
  #     ip: '192.168.87.78'
  #     username: 'admin'
  #     password: 'Gaura108'

modes:
  dual_0_topleft:
    type: 'dual_view'
    pos0: [859, 483]
    pos1: [0, 0]
    scale0: 33
    scale1: 80
  dual_1_topleft:
    type: 'dual_view'
    pos0: [859, 483]
    pos1: [0, 0]
    scale1: 33
    scale0: 80
  fullscreen_0:
    type: 'full_screen'
    pos: [0, 0]
    scale: 100
  fullscreen_1:
    type: 'full_screen'
    pos: [0, 0]
    scale: 100
  left_column_right_main:
    type: 'left_column_right_main'
    pos_left_top: [0, 0]
    pos_left_bottom: [0, 480]
    pos_right: [500, 0]
    scale_left: 32
    scale_right: 60
