background_image: '../assets/default_background.png'
cameras:
  # Mock camera with generated content
  - id: 0
    type: 'mock'
    source: 'generated'
    fps: 30
    width: 1920
    height: 1080
  
  # Mock camera with video file (if available)
  - id: 1
    type: 'mock'
    source: 'video'
    video_path: '../assets/sample_video.mp4'
    fps: 30
    loop: true
  
  # Mock camera with webcam fallback
  - id: 2
    type: 'mock'
    source: 'webcam'
    webcam_index: 0
    width: 1920
    height: 1080
    fps: 30

# Production IP cameras (commented out for development)
# cameras:
#   - id: 0
#     type: 'ip_camera'
#     rtsp_url: 'rtsp://admin:Gaura108@192.168.87.76:554/h264Preview_01_main'
#     https:
#       ip: '192.168.87.76'
#       username: 'admin'
#       password: 'Gaura108'
#   - id: 1
#     type: 'ip_camera'
#     rtsp_url: 'rtsp://admin:Gaura108@192.168.87.77:554/h264Preview_01_main'
#     https:
#       ip: '192.168.87.77'
#       username: 'admin'
#       password: 'Gaura108'
#   - id: 2
#     type: 'ip_camera'
#     rtsp_url: 'rtsp://admin:Gaura108@192.168.87.78:554/h264Preview_01_main'
#     https:
#       ip: '192.168.87.78'
#       username: 'admin'
#       password: 'Gaura108'

modes:
  fullscreen_0:
    type: 'full_screen'
    pos: [0, 0]
    scale: 100
  fullscreen_1:
    type: 'full_screen'
    pos: [0, 0]
    scale: 100
  dual_0_topleft_small_1_bottomright_large:
    type: 'dual_view'
    cam_top_left: 0
    pos_top_left: [0, 0]
    cam_bottom_right: 1
    pos_bottom_right: [768,432]
    scale_top_left: 40
    scale_bottom_right: 60
  dual_0_topleft_large_1_bottomright_small:
    type: 'dual_view'
    cam_top_left: 0
    pos_top_left: [0, 0]
    cam_bottom_right: 1
    pos_bottom_right: [1286,724]
    scale_top_left: 67
    scale_bottom_right: 33
  dual_1_topleft_small_0_bottomright_large:
    type: 'dual_view'
    cam_top_left: 1
    pos_top_left: [0, 0]
    cam_bottom_right: 0
    pos_bottom_right: [859, 483]
    scale_top_left: 33
    scale_bottom_right: 80
  dual_1_topleft_large_0_bottomright_small:
    type: 'dual_view'
    cam_top_left: 1
    pos_top_left: [0, 0]
    cam_bottom_right: 0
    pos_bottom_right: [859, 483]
    scale_top_left: 80
    scale_bottom_right: 33
  dual_2_topleft_small_1_bottomright_large:
    type: 'dual_view'
    cam_top_left: 2
    pos_top_left: [0, 0]
    cam_bottom_right: 1
    pos_bottom_right: [859, 483]
    scale_top_left: 33
    scale_bottom_right: 80
  dual_2_topleft_large_1_bottomright_small:
    type: 'dual_view'
    cam_top_left: 2
    pos_top_left: [0, 0]
    cam_bottom_right: 1
    pos_bottom_right: [859, 483]
    scale_top_left: 80
    scale_bottom_right: 33
  dual_1_topleft_small_2_bottomright_large:
    type: 'dual_view'
    cam_top_left: 1
    pos_top_left: [0, 0]
    cam_bottom_right: 2
    pos_bottom_right: [859, 483]
    scale_top_left: 33
    scale_bottom_right: 80
  dual_1_topleft_large_2_bottomright_small:
    type: 'dual_view'
    cam_top_left: 1
    pos_top_left: [0, 0]
    cam_bottom_right: 2
    pos_bottom_right: [859, 483]
    scale_top_left: 80
    scale_bottom_right: 33
  left_column_12_right_main_0:
    type: 'left_column_right_main'
    cam_left_top: 1
    pos_left_top: [0, 0]
    cam_left_bottom: 2
    pos_left_bottom: [0, 540]
    cam_right: 0
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_21_right_main_0:
    type: 'left_column_right_main'
    cam_left_top: 2
    pos_left_top: [0, 0]
    cam_left_bottom: 1
    pos_left_bottom: [0, 540]
    cam_right: 0
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_02_right_main_1:
    type: 'left_column_right_main'
    cam_left_top: 0
    pos_left_top: [0, 0]
    cam_left_bottom: 2
    pos_left_bottom: [0, 540]
    cam_right: 1
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_20_right_main_1:
    type: 'left_column_right_main'
    cam_left_top: 2
    pos_left_top: [0, 0]
    cam_left_bottom: 0
    pos_left_bottom: [0, 540]
    cam_right: 1
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_01_right_main_2:
    type: 'left_column_right_main'
    cam_left_top: 0
    pos_left_top: [0, 0]
    cam_left_bottom: 1
    pos_left_bottom: [0, 540]
    cam_right: 2
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58
  left_column_10_right_main_2:
    type: 'left_column_right_main'
    cam_left_top: 1
    pos_left_top: [0, 0]
    cam_left_bottom: 0
    pos_left_bottom: [0, 540]
    cam_right: 2
    pos_right: [807, 0]
    scale_left: 50
    scale_right: 58 